######################################################################
# Automatically generated by qmake (2.00a) Tue Jun 20 20:26:19 2006
######################################################################

TEMPLATE = app
CONFIG -= app_bundle
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .
QT += xml

# Input
HEADERS += rcc.h
SOURCES += main.cpp rcc.cpp
