all: ui_chatmainwindow.rb ui_chatsetnickname.rb

ui_chatmainwindow.rb: chatmainwindow.ui
	rbuic4 chatmainwindow.ui -o ui_chatmainwindow.rb

ui_chatsetnickname.rb: chatsetnickname.ui
	rbuic4 chatsetnickname.ui -o ui_chatsetnickname.rb

