all: ui_mainwindowbase.rb ui_previewdialogbase.rb

ui_mainwindowbase.rb: mainwindowbase.ui
	rbuic4 mainwindowbase.ui -o ui_mainwindowbase.rb

ui_previewdialogbase.rb: previewdialogbase.ui
	rbuic4 previewdialogbase.ui -o ui_previewdialogbase.rb

